services:
  api-development:
    build:
      context: ./api/
      args:
        API_MODE: "dev"
    volumes:
      - ./api:/app/api
    ports:
      - "8000:8000"
    command: flask --app api run --debug --host=0.0.0.0 --port=8000


  api-production:
    extends:
      service: api-development
    build:
      args:
        API_MODE: "prod"
    ports:
      - "8000:8000"
    command: gunicorn 'api:create_app()'
